# Generated by Django 4.2.7 on 2023-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=50, verbose_name='english')),
                ('russian_word', models.CharField(max_length=50, verbose_name='russian')),
            ],
        ),
    ]
